#we use java
language: java
#we use jdk11
jdk:
- openjdk11

sudo: required
 
services:
  - docker
  
before_install:
  - docker build -t kaskinas/cicd-applied-to-spring-boot-java-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kaskinas/cicd-applied-to-spring-boot-java-app
script:
  - ./mvnw clean install 
 