#we use java
language: java
#we use jdk11
jdk:
- openjdk11

sudo: required
 
services:
  - docker
  
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim
script:
  - ./mvnw clean install 
 